# packagelist.make
#
# This file is generated by the code in GeneratePackageList - DO NOT EDIT
#
# Created by Helge Heß
# Copyright © 2020 ZeeZide GmbH. All rights reserved.
#
# OK, the `packages_files` is essentially the primary.sqlite.gz I suppose.
# Using this we could avoid the hardcoding of the package hashes:

# "${ALX_BLOBSTORE_URL}/d12a..1537ff7fb02e/glibc-devel-2.26-34.amzn2.aarch64.rpm"
PACKAGE_NAMES = \
4461f737882f5aa04fa8f05df5a627bdb23d0d2644cb9711c271a0204fc5cbd1/gcc-7.3.1-6.amzn2.0.4.aarch64.rpm \
2e9e9bed3db2f72dd24b760137769730b37e350c54165c8b4d65d2e2d9c4f628/gcc-c++-7.3.1-6.amzn2.0.4.aarch64.rpm \
ec398b0fdc6d4a7fb176f17b3575ed9486a212f2dd192ced7c5e8393f78d9982/libgcc-7.3.1-6.amzn2.0.4.aarch64.rpm \
cdf5a306acb46a871bacdc81244db11f5d6a7f9ba440a51ff5c29f3704ef1347/glibc-2.26-34.amzn2.aarch64.rpm \
2214cb3c41cbf2ea4ae4b7aff0d56a8b150782e3f5da4052bcd1310eb50ea7f4/glibc-static-2.26-34.amzn2.aarch64.rpm \
316577844d7b7097a0bd7e729ca349bfca5497c54babd6975709428ed8ac1afc/glibc-devel-2.26-34.amzn2.aarch64.rpm \
6ab42d1d9c4464b1cdd05e11d74ff197d6df3277f299fe4a33f0e206cd6e91e7/glibc-headers-2.26-34.amzn2.aarch64.rpm \
c81e5d52f77a66c2719002260ec1ad2db087c30d23dfebd4256374ef6725c22a/kernel-headers-4.14.181-140.257.amzn2.aarch64.rpm \
64a976b9fe17f8d57f439639d7915e81a871133629b88117f41cb74308f4ae39/libicu-50.2-4.amzn2.aarch64.rpm \
554b5fb3778cf6d1af7dd895d19b3c2f3a8138d67c992590d9a7ece03712bec8/libicu-devel-50.2-4.amzn2.aarch64.rpm \
1a101e5cb201be1a0d30a8eb091eef87d9ff3e250430ac0ed16caea8c47b12c3/zlib-devel-1.2.7-18.amzn2.aarch64.rpm \
ed8335eedda49281d3491377065df17cf07095a6c12abe354d846a5432336a42/libuuid-2.30.2-2.amzn2.0.4.aarch64.rpm \
86b401b67058ff959f70188c0ef02a357d6ee1c5dbbee68f132079b45554c564/libuuid-devel-2.30.2-2.amzn2.0.4.aarch64.rpm \
e1cc680849652345fe9e2ba657673112add00d41a0b7d97069a5b17045aaf5e5/libedit-devel-3.0-12.20121213cvs.amzn2.0.2.aarch64.rpm \
5ec7f6e8b1c92d5f2b694a1d0cd6ab84c72a31defc13c35ae86c739e54be73e7/libxml2-static-2.9.1-6.amzn2.3.3.aarch64.rpm \
fe6b763232166a86548fad53f76f67d74eed3b9cbce4a8d606874a32a93b638e/libxml2-devel-2.9.1-6.amzn2.3.3.aarch64.rpm \
91a95245207ac34c1e191482e7d2469f049bbe1b1b2c7913b45b3ecf60da14c0/sqlite-devel-3.7.17-8.amzn2.1.1.aarch64.rpm \
61ca3394b68ad7787f9420c344bcc8e9cff4af385f46f92c2a4c8c0b107f4e3e/python-devel-2.7.18-1.amzn2.aarch64.rpm \
bae0cdcb07f6b37f37f732c07288872f8da426ae56d67d1bec22bc0448ddac37/ncurses-static-6.0-8.20170212.amzn2.1.3.aarch64.rpm \
73e279e857cefe7b6ba70d0198c26379e6625403744e117cd4d71ca86fc6deef/ncurses-devel-6.0-8.20170212.amzn2.1.3.aarch64.rpm \
ba351c16c9de2a36fcd25128df174e28ae82dcf5c58ec0ee8f648e6ba7f5327a/libcurl-devel-7.61.1-12.amzn2.0.1.aarch64.rpm \
39964f1e2e795f1d5cab9ea44c8f1ff01c3a2adf2d6eed78da1a89c18bc0a4d0/openssl-static-1.0.2k-19.amzn2.0.3.aarch64.rpm \
f9364e77a737e9edeadebe418c65a60567bf91535bd273fa6df3498d36643266/openssl-devel-1.0.2k-19.amzn2.0.3.aarch64.rpm \
0267ae3815ae1a300df82bfd244f17a799bcea2943cbcc57f164dc1f905e641e/libtool-2.4.2-22.2.amzn2.0.2.aarch64.rpm \
9a3dae46fffd3a7ae2636803c52c797f410441d6332ddcbad2aaa6e79b73f3a2/lua-devel-5.1.4-15.amzn2.0.2.aarch64.rpm \
db9eb934e62247fdc49724f98f0fbb5ea0a464786804f837c5ec01f2826187ca/lua-static-5.1.4-15.amzn2.0.2.aarch64.rpm \
e72c7ed308cea1b26517fd21d11add8b646069333f5235b083285d073657fdfe/libpng-devel-1.5.13-7.amzn2.0.2.aarch64.rpm \
a20a7e5443b37e9fbc0e9cf202b7528a0a03f1cec3408c236b628ab54cbda858/libpng-static-1.5.13-7.amzn2.0.2.aarch64.rpm \
bab874ed95af1e6f6649093de200a44bd6fd12146020bde401ad75c96bd6a5d9/libtiff-devel-4.0.3-32.amzn2.aarch64.rpm \
0bf0838c440d407970944f048bb6d47a55331d0b28e2926856e2d3095f985fe9/libtiff-static-4.0.3-32.amzn2.aarch64.rpm \
7617f64df9d7ef4467e6bd811b3e488d3317157e769c5ea0bd26705f57928a08/libuv-devel-1.23.2-1.amzn2.0.2.aarch64.rpm \
6fd1175ad41ae6c451fc8a94453558d56e400c7ba526282ebd5600488e78353c/libuv-static-1.23.2-1.amzn2.0.2.aarch64.rpm \
ea76c67426160f9a97cd197f2b17f1c3e4c3718fdceb3eb0dfc03901b763e7d0/lz4-devel-1.7.5-2.amzn2.0.1.aarch64.rpm \
a20c566bf810203846d02d2a1fd480273604c580d58ede737c01983bd87d28e5/lz4-static-1.7.5-2.amzn2.0.1.aarch64.rpm \
ff4dd68dc3f289bf4e82fd06971a98318d805cc83026eafa2ebba24c778a3156/pcre2-devel-10.23-2.amzn2.0.2.aarch64.rpm \
77b304ef1161c2c793459565b392ba0f22329322cb0bbef8954aa8428ecd7d4e/pcre2-static-10.23-2.amzn2.0.2.aarch64.rpm \
85124e32292dd939607cb4228ca4e3de5d30594ca560bcfccdcfaa282a3db5d5/popt-devel-1.13-16.amzn2.0.2.aarch64.rpm \
0b4de3a66d4620716a1ba8af89e43637310b21be50ee0e3bbfa8573f2c2fc200/popt-static-1.13-16.amzn2.0.2.aarch64.rpm \
2432be78a20a3fbd75e72a679543c960ce4c515e61d2ff44edf98e95b6827ac2/postgresql-devel-9.2.24-1.amzn2.0.1.aarch64.rpm \
b97644fbccbc971ffa7120cd346ac92645399df380b1eb083cccd10af4a5d88a/postgresql-static-9.2.24-1.amzn2.0.1.aarch64.rpm \
1b4300acd8ccd8908204a48fc13621db1e50ec704e2377a1fe55c4d417fe41b1/zlib-static-1.2.7-18.amzn2.aarch64.rpm \
3298eed07156409087d1270e96a6fc9817dea4a10e03bfc389e2bd36b25f3e52/libxml2-2.9.1-6.amzn2.3.3.aarch64.rpm \
080f23608c4811167f7947019c72f008c0a8971528012de3b696c257b1d33c65/sqlite-3.7.17-8.amzn2.1.1.aarch64.rpm \
fc5976cb3d917429dff29b6b21d817d3edf89c8a9e3812028a183989c07f03fd/libedit-3.0-12.20121213cvs.amzn2.0.2.aarch64.rpm \
56a470c48cf4662f2b9e849c88cc97e2e323e9ac2f5e022ebcb89843aa7dae28/ncurses-libs-6.0-8.20170212.amzn2.1.3.aarch64.rpm \
daea1e342cadc79f57b6c577ea70ddf0dc9a3ddb55852067cfd020e1d8916898/libcurl-7.61.1-12.amzn2.0.1.aarch64.rpm \
ec64e60e85279558c1ee2d613fe8339e6f7363c2b433674abcecf0ff94e02931/openssl-libs-1.0.2k-19.amzn2.0.3.aarch64.rpm \
758afe908d1844aaf9578ff43af8cc9766f0a36a249102543b7d90a6d995632b/lua-5.1.4-15.amzn2.0.2.aarch64.rpm \
aeb0879e8cd56d422cc5ff19d5dd7bce1629456404e494635f8f0ba5c9c63b28/libpng-1.5.13-7.amzn2.0.2.aarch64.rpm \
8f32b1f8651586fc94bf092206f73011f95a4c7c350fcdf719f30b36251efae7/lz4-1.7.5-2.amzn2.0.1.aarch64.rpm \
3105477fcb92a5c9c9bd2241ee58517d8179333902358ec5358503c07ae62f03/pcre2-10.23-2.amzn2.0.2.aarch64.rpm \
138e65213d34fe31d11c6bb22d7c02302079e0daed6089918c0c0a06b6e5c221/popt-1.13-16.amzn2.0.2.aarch64.rpm \
64e26947f546c7a0e4f847cd2acddf23a6e2b34231785d23abc708e46ec470d6/postgresql-libs-9.2.24-1.amzn2.0.1.aarch64.rpm \
b668f6084eebc7e6df7472c7f203e8d80247c4ce084bd23b314bd876d44007e9/zlib-1.2.7-18.amzn2.aarch64.rpm \
2b013e46aa8367a842bd475f21cebee3477f5b2b56ee0c38652b8631b601be68/tzdata-2019c-1.amzn2.noarch.rpm \
